services:
  - type: web
    name: housemaster-bot
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run bot
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: LANGUAGE
        value: ru
    autoDeploy: true
    region: frankfurt