services:
  - type: web
    name: housemaster-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node src/bot.js
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: LANGUAGE
        value: ru
    autoDeploy: true
    region: frankfurt